sudo: false

language: scala

jdk: openjdk8

scala:
  - 2.11.12
  - 2.12.10

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
    - MONGODB_FILE_NAME=mongodb-linux-x86_64-enterprise-ubuntu1404
    - MONGODB=4.0.0

addons:
  apt:
    packages:
      - libsnmp-dev

install:
  - wget http://downloads.mongodb.com/linux/${MONGODB_FILE_NAME}-${MONGODB}.tgz
  - tar xzf ${MONGODB_FILE_NAME}-${MONGODB}.tgz
  - ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/bin/mongod --version

before_script:
  - mkdir ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/data
  - ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/bin/mongod --dbpath ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/data --logpath ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/mongodb.log --setParameter enableTestCommands=1 --fork --smallfiles --nojournal

after_script:
  - pkill mongod
